use scrut::diff::DiffTool;
use scrut::expectation::ExpectationMaker;
use scrut::rules::registry::RuleRegistry;

use crate::rng::{hex, mbt, Rng};

const LINES: &[&str] = &["foo", "bar", "baz", "foo1", "foo2", "", "x y", "123"];
const EXPECTS: &[&str] = &[
    "foo", "bar", "baz", "foo1", "", "foo* (glob)", "foo* (glob+)", "foo* (glob*)", "ba? (glob?)",
    "foo (?)", "foo (*)", "foo (+)", "bar (+)", "bar (*)", "\\d+ (regex)", "\\d+ (regex+)",
    ".* (regex*)", ".* (regex+)", "x y", "foo (no-eol)", "bar (no-eol)", "foo\\x31 (escaped)",
    "* (glob*)", "baz (?)", "[a-z]+ (regex?)",
];

pub fn main() {
    let mut rng = Rng(0xd1ff_0000_1234);
    println!("// Generated by scripts/oracle (diff); DO NOT EDIT.\n");
    println!("///|\n/// (expectations, hex output, upstream Debug of the diff)");
    println!("let diff_cases : Array[(Array[String], String, String)] = [");
    let maker = ExpectationMaker::new(RuleRegistry::default());
    for _ in 0..3000 {
        let ne = rng.below(6);
        let exps: Vec<String> = (0..ne).map(|_| rng.pick(EXPECTS).to_string()).collect();
        let nl = rng.below(7);
        let mut out = String::new();
        for i in 0..nl {
            out.push_str(rng.pick(LINES));
            if i + 1 < nl || rng.chance(80) {
                out.push('\n');
            }
        }
        let expectations: Vec<_> = exps.iter().map(|e| maker.parse(e).unwrap()).collect();
        let diff = DiffTool::new(expectations).diff(out.as_bytes()).unwrap();
        let rendered = format!("{diff:?}");
        let list: Vec<String> = exps.iter().map(|e| mbt(e)).collect();
        println!("  ([{}], {}, {}),", list.join(", "), mbt(&hex(out.as_bytes())), mbt(&rendered));
    }
    println!("]");
}
