mod rng;
mod text;
mod rules;
mod diff;
mod parse;

use unicode_categories::UnicodeCategories;

/// Ranges of code points for which `char::is_other()` holds (general
/// category C: Cc, Cf, Cn, Co, Cs as known to unicode_categories 0.1.1).
fn tables() {
    let mut ranges: Vec<(u32, u32)> = vec![];
    for cp in 0u32..=0x10FFFF {
        let other = match char::from_u32(cp) {
            Some(c) => c.is_other(),
            None => true, // surrogates never reach the escaper as chars
        };
        if !other {
            continue;
        }
        match ranges.last_mut() {
            Some((_, hi)) if *hi + 1 == cp => *hi = cp,
            _ => ranges.push((cp, cp)),
        }
    }
    println!("// Generated by scripts/oracle (tables); DO NOT EDIT.");
    println!("// Code point ranges of Unicode general category C (`is_other`),");
    println!("// as known to the unicode_categories 0.1.1 crate upstream scrut uses.\n");
    println!("///|\nlet other_ranges : ReadOnlyArray[(Int, Int)] = [");
    for (lo, hi) in ranges {
        println!("  (0x{lo:X}, 0x{hi:X}),");
    }
    println!("]");
}

/// Code point ranges matching the regex crate's `\p{L}` (upstream's
/// Markdown title detection).
fn letter_table() {
    let re = regex::Regex::new(r"^\p{L}$").unwrap();
    let mut ranges: Vec<(u32, u32)> = vec![];
    for cp in 0u32..=0x10FFFF {
        let Some(c) = char::from_u32(cp) else { continue };
        if !re.is_match(c.encode_utf8(&mut [0; 4])) {
            continue;
        }
        match ranges.last_mut() {
            Some((_, hi)) if *hi + 1 == cp => *hi = cp,
            _ => ranges.push((cp, cp)),
        }
    }
    println!("// Generated by scripts/oracle (letters); DO NOT EDIT.");
    println!("// Code point ranges of `\\p{{L}}` (Unicode letters) per the regex crate.\n");
    println!("///|\nlet letter_ranges : ReadOnlyArray[(Int, Int)] = [");
    for (lo, hi) in ranges {
        println!("  (0x{lo:X}, 0x{hi:X}),");
    }
    println!("]");
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("tables") => tables(),
        Some("letters") => letter_table(),
        Some("text") => text::main(),
        Some("rules") => rules::main(),
        Some("diff") => diff::main(),
        Some("parse") => parse::main(),
        other => panic!("unknown mode {other:?}"),
    }
}
