use unicode_categories::UnicodeCategories;

/// Ranges of code points for which `char::is_other()` holds (general
/// category C: Cc, Cf, Cn, Co, Cs as known to unicode_categories 0.1.1).
fn tables() {
    let mut ranges: Vec<(u32, u32)> = vec![];
    for cp in 0u32..=0x10FFFF {
        let other = match char::from_u32(cp) {
            Some(c) => c.is_other(),
            None => true, // surrogates never reach the escaper as chars
        };
        if !other {
            continue;
        }
        match ranges.last_mut() {
            Some((_, hi)) if *hi + 1 == cp => *hi = cp,
            _ => ranges.push((cp, cp)),
        }
    }
    println!("// Generated by scripts/oracle (tables); DO NOT EDIT.");
    println!("// Code point ranges of Unicode general category C (`is_other`),");
    println!("// as known to the unicode_categories 0.1.1 crate upstream scrut uses.\n");
    println!("///|\nlet other_ranges : ReadOnlyArray[(Int, Int)] = [");
    for (lo, hi) in ranges {
        println!("  (0x{lo:X}, 0x{hi:X}),");
    }
    println!("]");
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("tables") => tables(),
        other => panic!("unknown mode {other:?}"),
    }
}
