//! Helpers of the command line: globset matching, `Path` operations and
//! UTF-8 error messages.

use std::path::Path;

use crate::rng::{hex, mbt, Rng};

const GLOB_PARTS: &[&str] = &[
    "*", "?", "**", "*.md", ".{md,markdown,scrut}", "{t,cram}", "[ab]", "[!a]", "[a-c]",
    "\\*", "a", "b", "/", "x.", "{a,}", "[", "}", "{",
];
const PATH_PARTS: &[&str] = &[
    "a", "b", "md", ".", "..", "/", "x.md", "y.t", "z.cram", "*", "é", "ab", "a.b.c", "{", "",
];

fn join(rng: &mut Rng, parts: &[&str], max: u64) -> String {
    (0..1 + rng.below(max)).map(|_| *rng.pick(parts)).collect()
}

pub fn main() {
    let mut rng = Rng(0x9105_eed5);
    println!("// Generated by scripts/oracle (misc); DO NOT EDIT.\n");
    println!("///|\n/// (glob, [(path, matches)]); `ERR` globs do not compile");
    println!("let glob_cases : Array[(String, Bool, Array[(String, Bool)])] = [");
    for _ in 0..1500 {
        let pattern = join(&mut rng, GLOB_PARTS, 4);
        let paths: Vec<String> = (0..6).map(|_| join(&mut rng, PATH_PARTS, 4)).collect();
        match globset::Glob::new(&pattern) {
            Err(_) => println!("  ({}, false, []),", mbt(&pattern)),
            Ok(g) => {
                let m = g.compile_matcher();
                let results: Vec<String> = paths
                    .iter()
                    .map(|p| format!("({}, {})", mbt(p), m.is_match(p)))
                    .collect();
                println!("  ({}, true, [{}]),", mbt(&pattern), results.join(", "));
            }
        }
    }
    println!("]\n");
    println!("///|\n/// (path, parent or `<none>`, file name, stem, extension or `<none>`)");
    println!("let path_cases : Array[(String, String, String, String, String)] = [");
    for _ in 0..1500 {
        let p = join(&mut rng, PATH_PARTS, 5);
        let path = Path::new(&p);
        let parent = path.parent().map_or("<none>".into(), |x| x.display().to_string());
        let name = path.file_name().map_or("".into(), |x| x.to_string_lossy().to_string());
        let stem = path.file_stem().map_or("".into(), |x| x.to_string_lossy().to_string());
        let ext = path.extension().map_or("<none>".into(), |x| x.to_string_lossy().to_string());
        println!(
            "  ({}, {}, {}, {}, {}),",
            mbt(&p),
            mbt(&parent),
            mbt(&name),
            mbt(&stem),
            mbt(&ext)
        );
    }
    println!("]\n");
    println!("///|\n/// (hex bytes, Rust's `Utf8Error` message or `<ok>`)");
    println!("let utf8_cases : Array[(String, String)] = [");
    let interesting: &[u8] = &[
        0x00, 0x41, 0x7f, 0x80, 0xbf, 0xc0, 0xc1, 0xc2, 0xdf, 0xe0, 0xed, 0xef, 0xf0, 0xf4, 0xf5,
        0xff, 0x9f, 0xa0, 0x8f, 0x90,
    ];
    for _ in 0..3000 {
        let n = rng.below(7) as usize;
        let bytes: Vec<u8> = (0..n).map(|_| *rng.pick(interesting)).collect();
        let msg = match std::str::from_utf8(&bytes) {
            Ok(_) => "<ok>".to_string(),
            Err(e) => e.to_string(),
        };
        println!("  ({}, {}),", mbt(&hex(&bytes)), mbt(&msg));
    }
    println!("]");
}
