use std::sync::Arc;

use scrut::config::TestCaseConfig;
use scrut::expectation::ExpectationMaker;
use scrut::parsers::cram::CramParser;
use scrut::parsers::markdown::MarkdownParser;
use scrut::parsers::parser::Parser;
use scrut::rules::glob_cram::CramGlobRule;
use scrut::rules::registry::RuleRegistry;
use scrut::rules::rule::RuleMaker;

use crate::rng::{mbt, Rng};

const TITLES: &[&str] = &[
    "A title", "# Heading", "## Sub heading", "#  spaced", "Élan vital", "123 not a title",
    "  indented para", "- list item", "**bold**", "#nospace",
];
const EXPECT: &[&str] = &[
    "foo", "bar (glob)", "ba* (glob+)", "\\d+ (regex)", "x (?)", "", "hello world", "[1]", "[42]",
    "a\\tb (escaped)", "$ not a command", "> not a continuation", "# not a comment", "% nope",
];
const CONFIG: &[&str] = &[
    "timeout: 10s", "environment: {A: b, C: \"d\"}", "output_stream: combined", "keep_crlf: true",
    "wait: 1s", "wait: {timeout: 2s, path: sock}", "detached_kill_signal: int",
    "detached_kill_signal: 9", "fail_fast: true", "skip_document_code: 42", "unknown: 1",
    "strip_ansi_escaping: true", "interpolated: true", "output_stream: stderr", "detached: true",
    "timeout: 1m 30s", "timeout: 1.5s", "environment: {Z: 1, A: 2}",
];
const DOC_CONFIG: &[&str] = &[
    "total_timeout: 30s", "defaults: {timeout: 5s}", "append: [a.md]", "prepend: [b.md, c.md]",
    "shell: /bin/zsh", "defaults:\n  environment:\n    X: y", "total_timeout: 15m",
];

fn command(rng: &mut Rng, cram: bool) -> Vec<String> {
    let p = if cram { "  " } else { "" };
    let mut out = vec![format!("{p}$ {}", rng.pick(&["echo hello", "ls -la", "a \\", "printf 'x'"]))];
    for _ in 0..rng.below(3) {
        out.push(format!("{p}> {}", rng.pick(&["more", "", "args \\"])));
    }
    if rng.chance(10) {
        out.push(format!("{p}>"));
    }
    out
}

fn markdown(rng: &mut Rng) -> String {
    let mut lines: Vec<String> = vec![];
    if rng.chance(30) {
        lines.push("---".into());
        for _ in 0..rng.below(3) {
            lines.push(rng.pick(DOC_CONFIG).to_string());
        }
        lines.push("---".into());
    }
    for _ in 0..1 + rng.below(4) {
        for _ in 0..rng.below(3) {
            if rng.chance(30) {
                lines.push(String::new());
            } else {
                lines.push(rng.pick(TITLES).to_string());
            }
        }
        if rng.chance(15) {
            lines.push(format!("```{}", rng.pick(&["python", "bash", "", "sh {x}"])));
            lines.push("print(1)".into());
            lines.push("```".into());
            continue;
        }
        let fence = if rng.chance(20) { "````" } else { "```" };
        if rng.chance(30) {
            let n = 1 + rng.below(2);
            let mut cfg: Vec<&str> = (0..n).map(|_| *rng.pick(CONFIG)).collect();
            // Duplicate keys: a known difference (the YAML library rejects them).
            cfg.sort_by_key(|c| c.split(':').next().unwrap_or("").to_string());
            cfg.dedup_by_key(|c| c.split(':').next().unwrap_or("").to_string());
            lines.push(format!("{fence}scrut {{{}}}", cfg.join(", ")));
        } else {
            lines.push(format!("{fence}scrut"));
        }
        if rng.chance(20) {
            lines.push("# a comment".into());
        }
        if rng.chance(25) {
            for _ in 0..1 + rng.below(2) {
                lines.push(format!("% {}", rng.pick(CONFIG)));
            }
        }
        if rng.chance(90) {
            lines.extend(command(rng, false));
        }
        for _ in 0..rng.below(4) {
            lines.push(rng.pick(EXPECT).to_string());
        }
        if lines.last().map_or(true, |l| l.starts_with(fence)) {
            lines.push("x".into());
        }
        lines.push(fence.to_string());
    }
    lines.join("\n") + if rng.chance(80) { "\n" } else { "" }
}

fn cram(rng: &mut Rng) -> String {
    let mut lines: Vec<String> = vec![];
    for _ in 0..1 + rng.below(4) {
        match rng.below(4) {
            0 => lines.push(String::new()),
            1 => lines.push(rng.pick(TITLES).to_string()),
            _ => {}
        }
        for _ in 0..1 + rng.below(2) {
            lines.extend(command(rng, true));
        }
        for _ in 0..rng.below(4) {
            let e = rng.pick(EXPECT);
            lines.push(format!("  {e}"));
        }
        if rng.chance(20) {
            lines.push("# comment".into());
        }
    }
    lines.join("\n") + "\n"
}

pub fn main() {
    std::panic::set_hook(Box::new(|_| {}));
    let mut rng = Rng(0x9a55_e11a);
    println!("// Generated by scripts/oracle (parse); DO NOT EDIT.\n");
    println!("///|\n/// (cram, document, result: `ERR` or config JSON + test case JSON lines)");
    println!("let parse_cases : Array[(Bool, String, String)] = [");
    for i in 0..2500 {
        let is_cram = i % 4 == 0;
        let doc = if is_cram { cram(&mut rng) } else { markdown(&mut rng) };
        let result = std::panic::catch_unwind(|| if is_cram {
            let mut registry = RuleRegistry::default();
            registry.register(CramGlobRule::make, &["glob", "gl"]);
            CramParser::new(Arc::new(ExpectationMaker::new(registry)), 2).parse(&doc)
        } else {
            MarkdownParser::new(
                Arc::new(ExpectationMaker::new(RuleRegistry::default())),
                &["scrut"],
                Some(TestCaseConfig::default_markdown()),
            )
            .parse(&doc)
        });
        let out = match result {
            Err(_) => "PANIC".to_string(),
            Ok(Err(_)) => "ERR".to_string(),
            Ok(Ok((config, testcases))) => {
                let mut s = serde_json::to_string(&config).unwrap();
                for t in testcases {
                    s.push('\n');
                    s.push_str(&t.to_string());
                }
                s
            }
        };
        println!("  ({is_cram}, {}, {}),", mbt(&doc), mbt(&out));
    }
    println!("]");
}
