//! Whole Rust regexes (without scrut's fix-ups) matched on sample lines
//! (`rules/pattern_oracle_cases_wbtest.mbt`): groups, flags, alternation,
//! repetitions, assertions and classes.

use crate::classes::class;
use crate::rng::{hex, mbt, Rng};

const LITERALS: &[&str] = &[
    "a", "b", "k", "s", "é", "É", "ß", "σ", "K", "\\u{212A}", "中", "😀", " ", "\\.", "\\*",
    "\\-", "\\#", "\\&", "\\~", "\\ ", "\\x41", "\\u0062", "\\x{e9}", "-", "#", "_", "1", "\\n",
    "\\t", "}", "]", "\\{", "\\}",
];
const CLASSES: &[&str] = &[
    ".", "\\w", "\\W", "\\d", "\\D", "\\s", "\\S", "\\pL", "\\p{Greek}", "\\PN", "\\p{Lu}",
    "[[:alpha:]]", "[^a]",
];
const ASSERTIONS: &[&str] = &["^", "$", "\\A", "\\z", "\\b", "\\B"];
const FLAGS: &[&str] = &["i", "-i", "s", "U", "x", "m", "i-s", "iU", "R", "-x", "ix"];

fn atom(rng: &mut Rng, depth: u32) -> String {
    match rng.below(if depth < 3 { 10 } else { 7 }) {
        0..=2 => rng.pick(LITERALS).to_string(),
        3 => rng.pick(CLASSES).to_string(),
        4 => class(rng, 1),
        5 => rng.pick(ASSERTIONS).to_string(),
        6 => format!("(?{})", rng.pick(FLAGS)),
        _ => {
            let open = match rng.below(6) {
                0 => "(".to_string(),
                1 => "(?:".to_string(),
                2 => format!("(?P<g{}>", rng.below(1000)),
                _ => format!("(?{}:", rng.pick(FLAGS)),
            };
            format!("{open}{})", alternation(rng, depth + 1))
        }
    }
}

fn quantified(rng: &mut Rng, depth: u32) -> String {
    let a = atom(rng, depth);
    // Large counts only for literals: Rust rejects `\w{300}` (its compiled
    // size limit), which is not modeled.
    let simple = LITERALS.contains(&a.as_str());
    let mut q = match rng.below(12) {
        0 => "*",
        1 => "+",
        2 => "?",
        3 => "{2}",
        4 => "{1,3}",
        5 => "{0,}",
        6 => "{2,}",
        7 if simple => "{300}",
        8 if simple => "{0,260}",
        _ => "",
    }
    .to_string();
    if !q.is_empty() {
        if rng.chance(25) {
            q.push('?');
        }
        if rng.chance(8) {
            q.push_str(rng.pick(&["*", "{2}", "?"]));
        }
    }
    format!("{a}{q}")
}

fn alternation(rng: &mut Rng, depth: u32) -> String {
    let branches = if rng.chance(30) { 2 + rng.below(2) } else { 1 };
    (0..branches)
        .map(|_| {
            let n = rng.below(4);
            let mut s: String = (0..n).map(|_| quantified(rng, depth)).collect();
            if rng.chance(10) {
                // `x` mode space and comments (literal elsewhere).
                s.push_str(rng.pick(&[" ", "  # note\n", "\t"]));
            }
            s
        })
        .collect::<Vec<_>>()
        .join("|")
}

const PIECES: &[&str] = &[
    "a", "b", "aa", "k", "K", "\u{212A}", "s", "S", "\u{17F}", "é", "É", "ß", "SS", "σ", "Σ",
    "ς", "中", "😀", " ", "  ", ".", "-", "#", "_", "1", "٣", "\t", "\r", "A", "e", "note",
    "{", "}", "*", "&", "~", "ab", "abc",
];

fn input(rng: &mut Rng) -> String {
    (0..rng.below(5)).map(|_| *rng.pick(PIECES)).collect()
}

pub fn main() {
    let mut rng = Rng(0x9a77_e2b5);
    println!("// Generated by scripts/oracle (patterns); DO NOT EDIT.\n");
    println!("///|\n/// (pattern, compiles, [(hex input, matches, matches `^(?:pattern)$`, the");
    println!("/// same two with ASCII word boundaries)]): Rust's `is_match`.");
    const CHUNK: usize = 300;
    const COUNT: usize = 1200;
    let ty = "Array[(String, Bool, Array[(String, Bool, Bool, Bool, Bool)])]";
    for i in 0..COUNT {
        if i % CHUNK == 0 {
            if i > 0 {
                println!("]\n\n///|");
            }
            println!("let pattern_cases_{} : {ty} = [", i / CHUNK);
        }
        let pattern = alternation(&mut rng, 0);
        match regex::bytes::Regex::new(&pattern) {
            Err(_) => println!("  ({}, false, []),", mbt(&pattern)),
            Ok(re) => {
                // A trailing `x` mode comment would swallow the `)$`.
                let Ok(whole) = regex::bytes::Regex::new(&format!("^(?:{pattern})$")) else {
                    println!("  // skipped: {}", mbt(&pattern));
                    continue;
                };
                // The same with ASCII word boundaries (the core engine's).
                let ascii = |p: &str| p.replace("\\b", "(?-u:\\b)").replace("\\B", "(?-u:\\B)");
                let re_ascii = regex::bytes::Regex::new(&ascii(&pattern)).unwrap();
                let whole_ascii =
                    regex::bytes::Regex::new(&format!("^(?:{})$", ascii(&pattern))).unwrap();
                let mut inputs: Vec<String> = (0..10).map(|_| input(&mut rng)).collect();
                inputs.push(String::new());
                let m: Vec<String> = inputs
                    .iter()
                    .map(|s| {
                        let b = s.as_bytes();
                        format!(
                            "({}, {}, {}, {}, {})",
                            mbt(&hex(b)),
                            re.is_match(b),
                            whole.is_match(b),
                            re_ascii.is_match(b),
                            whole_ascii.is_match(b)
                        )
                    })
                    .collect();
                println!("  ({}, true, [{}]),", mbt(&pattern), m.join(", "));
            }
        }
    }
    println!("]\n\n///|");
    let parts: Vec<String> = (0..COUNT / CHUNK).map(|k| format!("..pattern_cases_{k}")).collect();
    println!("let pattern_cases : {ty} = [{}]", parts.join(", "));
}
