use scrut::escaping::Escaper;
use scrut::expectation::ExpectationMaker;
use scrut::rules::glob_cram::CramGlobRule;
use scrut::rules::registry::RuleRegistry;
use scrut::rules::rule::RuleMaker;

use crate::rng::{hex, mbt, Rng};

const WORDS: &[&str] = &[
    "foo", "Hello", "bar baz", "a", "", " ", "x", "123", "é中文", "😀", "(equal)", "(glob)",
    "tab\there",
];
const GLOB: &[&str] = &["*", "?", "**", "\\*", "\\?", "\\\\", "a*b", "*x*"];
const REGEX: &[&str] = &[
    ".*", "\\d+", "\\d{3}", "[a-z]+", "[^0-9]", "(foo|bar)", "a{2,3}", "{x}", "\\[", "\\]",
    "[[]]", "\\_", "\\/", ".+?", "\\s*", "\\w", "^", "$", "\\.", "[0-9]{1,2}", "x?", "(?:ab)*",
    "\\x41", "\\p{L}", "\\bfoo\\b", "[[:digit:]]",
];
const ESC: &[&str] = &["\\t", "\\x1b", "\\x00", "\\\\", "\\e", "\\r", "\\0101", "\\x", "\\a"];
const KINDS: &[&str] = &[
    "", "equal", "eq", "no-eol", "escaped", "esc", "glob", "gl", "regex", "re", "unknown", "EQUAL",
];
const QUANTS: &[&str] = &["", "", "", "?", "*", "+"];

fn expression(rng: &mut Rng) -> String {
    let n = 1 + rng.below(4);
    (0..n)
        .map(|_| match rng.below(4) {
            0 => rng.pick(GLOB).to_string(),
            1 => rng.pick(REGEX).to_string(),
            2 => rng.pick(ESC).to_string(),
            _ => rng.pick(WORDS).to_string(),
        })
        .collect()
}

fn line(rng: &mut Rng) -> String {
    let expr = expression(rng);
    match rng.below(10) {
        0..=2 => expr,
        3 => format!("{expr} ()"),
        4 => format!("{expr}\t({}{})", rng.pick(KINDS), rng.pick(QUANTS)),
        5 => format!("{expr} ({}{}) (esc)", rng.pick(KINDS), rng.pick(QUANTS)),
        6 => format!("{expr} ({})", rng.pick(QUANTS)),
        _ => format!("{expr} ({}{})", rng.pick(KINDS), rng.pick(QUANTS)),
    }
}

fn output_lines(rng: &mut Rng, expr_line: &str) -> Vec<Vec<u8>> {
    let mut out = vec![];
    // The expression text itself and simple variants often match.
    let plain = expr_line.split(" (").next().unwrap_or("").to_string();
    out.push(format!("{plain}\n").into_bytes());
    out.push(plain.clone().into_bytes());
    for _ in 0..4 {
        let mut s = expression(rng).replace("\\t", "\t").replace("\\x1b", "\x1b");
        if rng.chance(70) {
            s.push('\n');
        }
        out.push(s.into_bytes());
    }
    out.push(b"foo\n".to_vec());
    out.push(b"\x1b\n".to_vec());
    out.push(b"tab\there\n".to_vec());
    out.push(b"123\n".to_vec());
    out
}

pub fn main() {
    let mut rng = Rng(0x7a11_5eed);
    println!("// Generated by scripts/oracle (rules); DO NOT EDIT.\n");
    println!("///|\n/// (cram, line, result, [(hex output line, matches)])");
    println!("/// result: `ERR` or `kind|hex expression|optional|multiline|original|ascii|unicode`");
    println!("let rule_cases : Array[(Bool, String, String, Array[(String, Bool)])] = [");
    for i in 0..3000 {
        let cram = i % 3 == 0;
        let mut registry = RuleRegistry::default();
        if cram {
            registry.register(CramGlobRule::make, &["glob", "gl"]);
        }
        let maker = ExpectationMaker::new(registry);
        let l = line(&mut rng);
        match maker.parse(&l) {
            Err(_) => println!("  ({cram}, {}, \"ERR\", []),", mbt(&l)),
            Ok(e) => {
                let (kind, expr, optional, multiline) = e.unmake();
                let result = format!(
                    "{kind}|{}|{optional}|{multiline}|{}|{}|{}",
                    hex(&expr),
                    e.original_string(),
                    e.to_expression_string(&Escaper::Ascii),
                    e.to_expression_string(&Escaper::Unicode),
                );
                let matches: Vec<String> = output_lines(&mut rng, &l)
                    .iter()
                    .map(|o| format!("({}, {})", mbt(&hex(o)), e.matches(o)))
                    .collect();
                println!("  ({cram}, {}, {}, [{}]),", mbt(&l), mbt(&result), matches.join(", "));
            }
        }
    }
    println!("]");
}
