use scrut::escaping::Escaper;
use scrut::expectation::ExpectationMaker;
use scrut::rules::glob_cram::CramGlobRule;
use scrut::rules::registry::RuleRegistry;
use scrut::rules::rule::RuleMaker;

use crate::rng::{hex, mbt, Rng};

const WORDS: &[&str] = &[
    "foo", "Hello", "bar baz", "a", "", " ", "x", "123", "é中文", "😀", "(equal)", "(glob)",
    "tab\there",
];
const GLOB: &[&str] = &["*", "?", "**", "\\*", "\\?", "\\\\", "a*b", "*x*"];
const REGEX: &[&str] = &[
    ".*", "\\d+", "\\d{3}", "[a-z]+", "[^0-9]", "(foo|bar)", "a{2,3}", "{x}", "\\[", "\\]",
    "[[]]", "\\_", "\\/", ".+?", "\\s*", "\\w", "^", "$", "\\.", "[0-9]{1,2}", "x?", "(?:ab)*",
    "\\x41", "\\p{L}", "\\bfoo\\b", "[[:digit:]]", "\\w+", "\\W", "\\d", "\\D", "[\\w]+", ".+",
    // Inline flags, Unicode classes and class set operations.
    "(?i)é", "(?i:é)", "(?i)k", "(?i)σ+", "(?i)straße", "(?i)[a-zé]+", "(?i:ǅ)", "(?-i)x",
    "(?x) a b # c", "(?x)[ a ]", "(?s).", "(?U)a+", "(?U).+?", "(?m)^", "(?R).", "(?-u:\\w)",
    "\\p{Greek}+", "\\p{Lu}", "\\pL", "\\P{L}", "\\p{sc=Grek}", "\\p{ Is_Greek }",
    "\\p{gc!=Lu}", "\\p{Nd}+", "\\p{Han}", "\\p{Emoji}", "\\p{Nope}",
    "[\\w&&\\p{Latin}]", "[a-z--[aeiou]]", "[\\d~~[0-5]]", "[[:^alpha:]]", "[a-]", "[-a]",
    "[]a]", "[^\\p{L}\\d]", "[\\p{Greek}\\d]+", "[^\\W\\d]", "\\w+", "\\d", "\\s",
    "\\x{212A}", "\\u{1F600}", "(?<name>x)", "(?P<n>é)?", "\\B",
];
/// Non-ASCII output lines the Unicode-aware patterns above can match.
const UNICODE_LINES: &[&str] = &[
    "αβγ\n", "ΑΒΓ\n", "\u{212A}\n", "k\n", "K\n", "É\n", "é\n", "STRASSE\n", "straße\n",
    "STRAẞE\n", "ǅ\n", "ǆ\n", "Σς\n", "σσ\n", "a b\n", "ab\n", "\u{663}\u{664}\n",
    "漢字\n", "😀\n", "x\u{301}\n", "Ωmega\n", "ÿ\n", "_\n", " \n", "\u{3000}\n",
];
const ESC: &[&str] = &["\\t", "\\x1b", "\\x00", "\\\\", "\\e", "\\r", "\\0101", "\\x", "\\a"];
const KINDS: &[&str] = &[
    "", "equal", "eq", "no-eol", "escaped", "esc", "glob", "gl", "regex", "re", "unknown", "EQUAL",
];
const QUANTS: &[&str] = &["", "", "", "?", "*", "+"];

fn expression(rng: &mut Rng) -> String {
    let n = 1 + rng.below(4);
    (0..n)
        .map(|_| match rng.below(4) {
            0 => rng.pick(GLOB).to_string(),
            1 => rng.pick(REGEX).to_string(),
            2 => rng.pick(ESC).to_string(),
            _ => rng.pick(WORDS).to_string(),
        })
        .collect()
}

fn line(rng: &mut Rng) -> String {
    let expr = expression(rng);
    match rng.below(10) {
        0..=2 => expr,
        3 => format!("{expr} ()"),
        4 => format!("{expr}\t({}{})", rng.pick(KINDS), rng.pick(QUANTS)),
        5 => format!("{expr} ({}{}) (esc)", rng.pick(KINDS), rng.pick(QUANTS)),
        6 => format!("{expr} ({})", rng.pick(QUANTS)),
        _ => format!("{expr} ({}{})", rng.pick(KINDS), rng.pick(QUANTS)),
    }
}

/// A line with a regex expectation built from regex pieces and words.
fn regex_line(rng: &mut Rng) -> String {
    let n = 1 + rng.below(4);
    let expr: String = (0..n)
        .map(|_| {
            if rng.chance(65) {
                rng.pick(REGEX).to_string()
            } else {
                rng.pick(WORDS).to_string()
            }
        })
        .collect();
    format!("{expr} ({}{})", rng.pick(&["re", "regex"]), rng.pick(QUANTS))
}

fn output_lines(rng: &mut Rng, expr_line: &str) -> Vec<Vec<u8>> {
    let mut out = vec![];
    // The expression text itself and simple variants often match.
    let plain = expr_line.split(" (").next().unwrap_or("").to_string();
    out.push(format!("{plain}\n").into_bytes());
    out.push(plain.clone().into_bytes());
    for _ in 0..4 {
        let mut s = expression(rng).replace("\\t", "\t").replace("\\x1b", "\x1b");
        if rng.chance(70) {
            s.push('\n');
        }
        out.push(s.into_bytes());
    }
    out.push(b"foo\n".to_vec());
    out.push(b"\x1b\n".to_vec());
    out.push(b"tab\there\n".to_vec());
    out.push(b"123\n".to_vec());
    // Invalid UTF-8 and non-ASCII word characters and digits.
    out.push(rng.pick(&[&b"\xffbad\n"[..], b"a\xc3\n", b"\xff", b"foo\x80\n"]).to_vec());
    out.push(rng.pick(&[&b"cr\rcr\n"[..], b"a\x0bb\n", b"\xc2\x85\n", b"x\xe2\x80\xa8y\n"]).to_vec());
    out.push(rng.pick(&["\u{65e5}\u{672c}\n", "\u{e9}\n", "\u{663}\n", "\u{24b6}\n", "x\u{301}\n"]).as_bytes().to_vec());
    for _ in 0..3 {
        out.push(rng.pick(UNICODE_LINES).as_bytes().to_vec());
    }
    out
}

pub fn main() {
    let mut rng = Rng(0x7a11_5eed);
    println!("// Generated by scripts/oracle (rules); DO NOT EDIT.\n");
    println!("///|\n/// (cram, line, result, [(hex output line, matches)])");
    println!("/// result: `ERR` or `kind|hex expression|optional|multiline|original|ascii|unicode`");
    // In chunks: one table would exceed MoonBit's text segment limit.
    const CHUNK: usize = 500;
    // General cases, then cases with regex expectations only.
    const GENERAL: usize = 3000;
    const TOTAL: usize = 5000;
    let ty = "Array[(Bool, String, String, Array[(String, Bool)])]";
    for i in 0..TOTAL {
        if i % CHUNK == 0 {
            if i > 0 {
                println!("]\n\n///|");
            }
            println!("let rule_cases_{} : {ty} = [", i / CHUNK);
        }
        let cram = i % 3 == 0;
        let mut registry = RuleRegistry::default();
        if cram {
            registry.register(CramGlobRule::make, &["glob", "gl"]);
        }
        let maker = ExpectationMaker::new(registry);
        let l = if i < GENERAL { line(&mut rng) } else { regex_line(&mut rng) };
        match maker.parse(&l) {
            Err(_) => println!("  ({cram}, {}, \"ERR\", []),", mbt(&l)),
            Ok(e) => {
                let (kind, expr, optional, multiline) = e.unmake();
                let result = format!(
                    "{kind}|{}|{optional}|{multiline}|{}|{}|{}",
                    hex(&expr),
                    e.original_string(),
                    e.to_expression_string(&Escaper::Ascii),
                    e.to_expression_string(&Escaper::Unicode),
                );
                let matches: Vec<String> = output_lines(&mut rng, &l)
                    .iter()
                    .map(|o| format!("({}, {})", mbt(&hex(o)), e.matches(o)))
                    .collect();
                println!("  ({cram}, {}, {}, [{}]),", mbt(&l), mbt(&result), matches.join(", "));
            }
        }
    }
    println!("]\n\n///|");
    let parts: Vec<String> = (0..TOTAL / CHUNK).map(|k| format!("..rule_cases_{k}")).collect();
    println!("let rule_cases : {ty} = [{}]", parts.join(", "));
}
