use scrut::escaping::{strip_colors_bytes, Escaper};

use crate::rng::{hex, mbt, Rng};

const PIECES: &[&[u8]] = &[
    b"a", b"Hello", b" ", b"\\", b"\\x", b"\t", b"\n", b"\r", b"\r\n", b"\x00", b"\x07", b"\x08",
    b"\x0b", b"\x0c", b"\x1b", b"\x7f", b"\x80", b"\x9f", b"\xff", b"\xc3", b"\xc3\xa9",
    "中文".as_bytes(), "\u{200b}".as_bytes(), "\u{ad}".as_bytes(), "\u{85}".as_bytes(),
    "😀".as_bytes(), "\u{feff}".as_bytes(), "\u{e000}".as_bytes(), b"\xe2\x82", b"\xf0\x9f\x98",
    b"\xed\xa0\x80", b"\xf4\x90\x80\x80", b"\xe0\x80\x80", b"\xc0\x80",
    b"\x1b[31m", b"\x1b[0m", b"\x1b[1;31;4m", b"\x1b]0;title\x07", b"\x1b]8;;http://x\x1b\\",
    b"\x1bP1$r\x1b\\", b"\x1b(B", b"\x1b[?25l", b"\x1b[2J", b"\x1b%G", b"\x1bX data \x1b\\",
    b"\x9b31m", b"\x18", b"\x1a", b"\x1b[", b"\x1b]", b"\x1bP", b"\x1b[12;", b"\x1b[>c",
];

fn random_bytes(rng: &mut Rng) -> Vec<u8> {
    let n = rng.below(8);
    let mut out = vec![];
    for _ in 0..n {
        if rng.chance(20) {
            out.push(rng.next() as u8);
        } else {
            out.extend_from_slice(rng.pick(PIECES));
        }
    }
    out
}

pub fn main() {
    let mut rng = Rng(0x5c7u64 << 40 | 0x1234_5678);
    println!("// Generated by scripts/oracle (text); DO NOT EDIT.\n");
    println!("///|\n/// (hex input, printable ascii, printable unicode, expectation ascii,");
    println!("/// expectation unicode, has_unprintable ascii, has_unprintable unicode)");
    println!("let escape_cases : Array[(String, String, String, String, String, Bool, Bool)] = [");
    let mut inputs: Vec<Vec<u8>> = PIECES.iter().map(|p| p.to_vec()).collect();
    for _ in 0..1500 {
        inputs.push(random_bytes(&mut rng));
    }
    for input in &inputs {
        println!(
            "  ({}, {}, {}, {}, {}, {}, {}),",
            mbt(&hex(input)),
            mbt(&Escaper::Ascii.escaped_printable(input)),
            mbt(&Escaper::Unicode.escaped_printable(input)),
            mbt(&Escaper::Ascii.escaped_expectation(input)),
            mbt(&Escaper::Unicode.escaped_expectation(input)),
            Escaper::Ascii.has_unprintable(input),
            Escaper::Unicode.has_unprintable(input),
        );
    }
    println!("]\n");
    println!("///|\n/// (hex input, hex stripped)");
    println!("let strip_cases : Array[(String, String)] = [");
    for input in &inputs {
        println!("  ({}, {}),", mbt(&hex(input)), mbt(&hex(&strip_colors_bytes(input))));
    }
    println!("]");
}
