#!/usr/bin/env python3
"""Oracle for argv/: how bash splits random command strings into words.

For each string S, runs `bash -c "printf '%s\\0' __W__ S"` and records the
words (or that bash failed). Writes argv/oracle_cases_test.mbt.
"""
import random
import tempfile
import subprocess
import sys

PIECES = [
    "a", "b", "foo", "x y", " ", "  ", "\t", "'", '"', "\\", "\\\n", "\n", "'a b'", '"a b"',
    '"\\""', '"\\$"', '"\\x"', "'\\'", '""', "''", "=", "A=b", "_x=1", "1=2", "~", "~/x",
    "#", "a#b", "!", "|", ";", "&", "<", ">", "(", ")", "`", "$", "$HOME", "*", "?", "[", "]",
    "{", "}", ",", "é", "中", "😀", "a\\ b", '"a\\\\b"', "'\"'", '"\'"', "-n", "--flag=v",
    '"\n"', "'\n'", "X=~", "X=a:~", "%", "^", "@", ":",
    '"$FOO"', '"${FOO}x"', '"$FOO_bar"', '"$UNSET"', '"${EMPTY}"', '"$X1"', '"a$FOO"',
    '"$1"', '"$?"', '"${FOO:-x}"', '"$RANDOM"', '"$"', '"${"', '"$STAR"', '"$TESTDIR/f"',
    'X="$FOO"', '"$FOO$X1"', '"${X1}${FOO}"', '"\\$FOO"', "'$FOO'", '"$FOO"\'$X1\'',
]

# Globs must not match anything.
EMPTY_DIR = tempfile.mkdtemp(prefix="argv-oracle.")

# Variables of the bash environment (also passed to our tokenizer).
ENV = {"PATH": "/usr/bin:/bin", "LC_ALL": "C.UTF-8", "FOO": "a b", "EMPTY": "",
       "X1": "x1", "STAR": "*", "TESTDIR": "/t d"}


def mbt(s):
    out = ['"']
    for c in s:
        if c == '"':
            out.append('\\"')
        elif c == "\\":
            out.append("\\\\")
        elif c == "\n":
            out.append("\\n")
        elif c == "\t":
            out.append("\\t")
        elif c == "\r":
            out.append("\\r")
        elif ord(c) < 0x20:
            out.append("\\u{%x}" % ord(c))
        else:
            out.append(c)
    out.append('"')
    return "".join(out)


def bash_words(s):
    script = "printf '%s\\0' __W__ " + s
    p = subprocess.run(["bash", "--norc", "--noprofile", "-c", script], capture_output=True,
                       env=ENV, cwd=EMPTY_DIR)
    if p.returncode != 0 or p.stderr:
        return None
    words = p.stdout.decode("utf-8", "replace").split("\0")[:-1]
    if not words or words[0] != "__W__":
        return None
    return words[1:]


def main():
    rng = random.Random(0xA56)
    cases = []
    for _ in range(4000):
        s = "".join(rng.choice(PIECES) for _ in range(rng.randint(1, 6)))
        cases.append((s, bash_words(s)))
    print("// Generated by scripts/argv_oracle.py; DO NOT EDIT.\n")
    print("///|\n/// The environment of the commands.")
    print("let argv_env : Array[(String, String)] = [")
    for k, v in ENV.items():
        print(f"  ({mbt(k)}, {mbt(v)}),")
    print("]\n")
    print("///|\n/// (command, bash's words or None when bash fails)")
    print("let argv_cases : Array[(String, Array[String]?)] = [")
    for s, words in cases:
        w = "None" if words is None else "Some([" + ", ".join(mbt(x) for x in words) + "])"
        print(f"  ({mbt(s)}, {w}),")
    print("]")


main()
